### ISSUE TITLE
Inconsistent patchState behaviour

### ISSUE THREAD

**Issue by fabriziodemaria** [spotify/styx#6]
If a user patches the state for a Workflow/Component calling the related API, the following can happen:

- At first, the user patches the Docker image for the specific pair `Component/Workflow`;
- Afterwards, the user patches the Docker image for the `Component`, expecting it to be picked up by all the Workflows within the Component;

The Docker image at Workflow level is always returned first when preparing executions, so the new configuration at Component level will not be picked up.

**Comment by ukarlsson** [comment]
We have a use case in bq-runner (https://ghe.spotify.net/bigquery/bigquery-runner) that is very similar to bq-load and in this use case `docker_image` in `data-info.yaml` is very useful so we are a bit worried about the deprecation of this field. In addition, we would also like to have a way of clearing the HTTP posted docker image since it overrides `data-info.yaml`. I actually think it would make more sense to have `data-info.yaml` override the HTTP post, and if the precedence was changed in this manner, we would not need to remove the HTTP posted version.

**Comment by fabriziodemaria** [comment]
After ##318 #296 this issue should be now resolved. The only way to set a Docker image is now via the API call for a specific workflow.
